### ISSUE TITLE
Synchronise with SVN automatically

### ISSUE THREAD

**Issue by tkw1536** [KWARC/bibs#1]
We should really keep this repository up-to-date from SVN automatically via a POST-commit hook, similar to the one we have for the MMT repository. 

@kohlhase What do you think? If needed I can set one up.

**Comment by kohlhase** [comment]
I would like this.

**Comment by tkw1536** [comment]
I will set one up tomorrow then.

**Comment by tkw1536** [comment]
1) I have configured a post-commit hook which does what its supposed to do. Please re-clone this github repository and no longer commit to it in the future as all changes will be overwritten by the SVN. 

2) The hook seems to cause errors some of the time and I am not sure if that was already the case before. I will do some more testing tomorrow.

**Comment by tkw1536** [comment]
@kohlhase Was there always a post-commit hook error when committing to the repository? The problem seems to be in the part of the code that generates kwarc.bib

**Comment by kohlhase** [comment]
yes, there was this error always, to alert people that they need to update `kwarc.bib`.

**Comment by tkw1536** [comment]
OK, in that case automatic synchronization is working properly.

**Comment by kohlhase** [comment]
thanks a lot, this is very useful.

**Comment by kohlhase** [comment]
BTW, is synchronization working in both directions?

**Comment by tkw1536** [comment]
Unfortunately no, that would be a lot more complicated, only SVN -> github.

**Comment by tkw1536** [comment]
I have an idea on how to improve it, but that would require a bit more cleanup. We can talk about it when you get back from Japan.

**Comment by kohlhase** [comment]
I was thinking so. But now I know what to do.
