### ISSUE TITLE
Possible typo in Normens name

### ISSUE THREAD

**Issue by tkw1536** [KWARC/bibs#10]
In several places we have "Normen Müuller". It looks to me like that is a typo and should actually be Normen Müller. 

@kohlhase Can you confirm?

**Comment by kohlhase** [comment]
yes, I can. Please change it globall.

**Comment by tkw1536** [comment]
Fixed and pushed, the website may take a few minutes to update completly.

**Comment by kohlhase** [comment]
thanks.
