### ISSUE TITLE
document how to add a person or a project to the pubs generation in the README.md

### ISSUE THREAD

**Issue by kohlhase** [KWARC/bibs#13]
We should generate publications for all the KWARC people (or at least all with publications).
So we should know all the places where we have to add the name. 
I would guess that Theresa and Jonas will come soon.

**Comment by tkw1536** [comment]
In general the steps are:
1. Update the `bib.people` variable in the [Makefile](https://github.com/KWARC/bibs/blob/master/Makefile#L9) and add the username of the person to add
2. Update the `<xsl:choose>` statement in [publist.xsl](https://github.com/KWARC/bibs/blob/master/src/pubs/publist.xsl#L9) to set the real name of the person to be added. 
I will add this to the README once I have the time.

**Comment by kohlhase** [comment]
I did this now.
