### ISSUE TITLE
document the html bibliographies building process in the README.md

### ISSUE THREAD

**Issue by kohlhase** [KWARC/bibs#14]
We should have a short paragraph in the README.md of master to say that we are building publication listings for persons and projects/systems via LaTeXML and say that to see things you should just go to the gh-pages branch. 
Then we should document in a README.md on gh-pages how the generation works. 
Otherwises I will always forget.

**Comment by tkw1536** [comment]
Fixed, see https://github.com/KWARC/bibs#the-build-process
