### ISSUE TITLE
add theses bibliographies. 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/bibs#16]
I have annotated all of kwarcpubs.bib with the three keywords `phdthesis`, `mscthesis`, `bscthesis`, from which I would like to generate four publication gh-pages: the three obivous ones and a combined one. 
I guess that this should be easy to do for Tom. 

It would be really good to have this soon.

**Comment by tkw1536** [comment]
We have the former, not sure we got the latter.

**Comment by kohlhase** [comment]
There is a generated page https://kwarc.github.io/bibs/theses/ but it is empty. I would have liked this to be the union of https://kwarc.github.io/bibs/bscthesis/ https://kwarc.github.io/bibs/mscthesis/ and https://kwarc.github.io/bibs/phdthesis/ (all of them seem to empty at the moment).

**Comment by tkw1536** [comment]
The emptyness bug has been fixed. 
Not sure why Masters Project Reports and Bachelors Project Reports aren't showing up right now.

**Comment by tkw1536** [comment]
Closing in favor of #28
