### ISSUE TITLE
Deployment lower-cases titles after a colon (e.g. FrameIT: ... lower case ...)

### ISSUE THREAD

**Issue by ComFreek** [KWARC/bibs#24]
Example tuples `(deployed title, bib source code)` from https://kwarc.github.io/bibs/ and this repo:

- FrameIT: detangling knowledge management from game design in serious games

    `{{FrameIT}: Detangling Knowledge Management from Game Design in Serious Games}`
- GLIF: a declarative framework for symbolic natural language understanding

    `{{GLIF}: A Declarative Framework for Symbolic Natural Language Understanding}`
- KAT: an annotation tool for STEM documents

  `{{KAT}: an Annotation Tool for {STEM} Documents}`

Is the lower-casing intended?

**Comment by ComFreek** [comment]
- Rapid prototyping formal systems in mmt: 5 case studies

  `{Rapid Prototyping Formal Systems in MMT: 5 Case Studies}`

Apparently it also lower-cases before the colon. So every time there is at least one colon, it lower cases everything not enclosed in `{}`?

**Comment by tkw1536** [comment]
This corresponds to BiBTeX's "title case" and isn't an issue with this repo in particular.

**Comment by tkw1536** [comment]
Concretely, the BiBTeX style used by this project uses the bibtex built-in function `change.case$` with the `t` parameter. This is a function that changes  every character in a string to lower-case with the following exceptions:
- the first character;
- anything is braces; and
- the first non-whitespace character following a colon.

These are left as-is. For details, see the [BiBTeX source code](https://github.com/MiKTeX/miktex/blob/master/Programs/Bibliography/bibtex/source/bibtex.web#L8859-L8907), emphasis mine:

> The `built_in` function `change.case$` pops the top two (string) literals; it changes the case of the second according to the specifications of the first, as follows.  (Note: The word `letters` in the next sentence refers only to those at `brace-level 0`, the top-most brace level; no other characters are changed, except perhaps for special characters, described shortly.)  If the first literal is the string `t`, __it converts to lower case all letters except the very first character in the string, which it leaves alone, and except the first character following any `colon` and then nonnull `white_space`, which it also leaves alone__; if it's the string `l`, it converts all letters to lower case; if it's the string `u`, it converts all letters to upper case [...].

**Comment by tkw1536** [comment]
I don't consider this a bug in the project, so I am closing this issue. If you believe the casing of titles should be maintained, please enclose the appropriate titles in extra `{}`s.

**Comment by ComFreek** [comment]
@tkw1536 Thank you very much for digging out this documentation!

If I am not mistaken, titles in LNCS-style bibs are always typeset as-is -- which would also be my preferred (uninformed) position. But I don't think I am in a position to unilaterally push that request onto this repo, so I won't modify any titles.
