### ISSUE TITLE
The "changes? if no, skip Travis" check produces false negatives

### ISSUE THREAD

**Issue by ComFreek** [KWARC/bibs#27]
Currently, the `deploy.sh` script running on Travis abort if it notices that no bib source files have changed in the commit for which Travis is running:

https://github.com/KWARC/bibs/blob/f664f07f6d148795885fe014b2a8196f3fc8eb61/src/travis/deploy.sh#L16-L21

This procudes too many false negatives when pushing multiple commits at once. In both cases below, Travis only considers the most recent commit.

- consider two *local-only* commits, where the first changes a source file, and the second one something else. When *pushing* those commits (two-in-one), the latter commit will make the script above prematurely abort.
- consider doing a local commit, then merging upstream changes via `git pull`, and then pushing.

Probably this is too minor to warrant fixing; feel free to close.

**Comment by tkw1536** [comment]
One way of avoiding this would be forcing travis to work on every commit. 
But IMO we really should be doing some kind of content hash to detect changes. 
And we should move to GitHub Actions because of recent Travis CI changes, meaning we won't get many resources anymore.
