### ISSUE TITLE
commit back the generated html, so that we can use them from kwarc.info

### ISSUE THREAD

**Issue by kohlhase** [KWARC/bibs#4]
If I understand correctly, then travis already builds the html files. Would it be possible to commit them back so that we can use them from kwarc.info? Then we could  fully shut down http://old.kward.info, which would be very good. 
@jbs1 @m-iancu

**Comment by tkw1536** [comment]
The html is committed on the [gh-pages](https://github.com/KWARC/bibs/tree/gh-pages) branch and served at https://kwarc.github.io/bibs/ after every commit.

**Comment by kohlhase** [comment]
Ah, thanks, "wer lesen kann ist klar im Vorteil"  :-(.
