### ISSUE TITLE
pull back crossreferences

### ISSUE THREAD

**Issue by kohlhase** [KWARC/bibs#7]
The main problem with the current publication list generation process is the `crossref` field in the bibTeX. This leads to wrong results and inflated counts, see https://github.com/brucemiller/LaTeXML/issues/800 for details. Once this is fixed, we can acually use the publication lists in kwarc.info.

**Comment by kohlhase** [comment]
cc: @tkw1536 for reference (and later scripting help). 

I have looked at what we can do without relying on LaTeXML to do the work for us. Currently the generation process is as follows. 
1. `latexmlc --bibtex *.bib` --> `*.bib.xml`
2. generate person-specific LaTeX files, e.g. `kohlhase-articles.tex` 
3. run `latexmlc` on those
4. assemble them by a stylesheet into a publication list. 
I guess what we could do is to fix up the `*.bib.xml` after  step 1. with an XSLT style sheet that pulls back the crossrefs. That should fix the problem. 

I will try to make such a stylesheet and report back.

**Comment by kohlhase** [comment]
OK, I have hacked something (but could only insufficiently test locally), so It seems that I broke things. @tkw1536 can you please help me? Here is what I did: 
- I updated the `Makefile` to generate a file `dist/ltxml/kcr.bib.xml` (I think that this should work; kcr.bib is just `cat kwarcpubs.bib kwarcrossrefs.bib extcrossrefs.bib`. 
- I updated the script `generate-html` to use `--bibliography kcl.bib.xml` (this is all we need). 
  I just see that I had a typo there, so let's see whether that fixes the problem.

**Comment by kohlhase** [comment]
If I only had a way to see the travis logs, ... 
Oh, and I have probably not cleaned up properly after myself.

**Comment by tkw1536** [comment]
Travis seems to be getting a lot of errors now. You can find the log of the latest build at https://travis-ci.org/KWARC/bibs/builds/164224521 . To update the travis build you should probably have a look at the build script https://github.com/KWARC/bibs/blob/master/src/travis/deploy.sh and of course the Makefile. In short, the travis build uses three targets:
1. `make clean` - to remove all old generated files (including kwarc.bib)
2. `make bib` - to generate the new `kwarc.bib`
3. `make pubs` - to generate a new publications website in the `pubs/` directory. 

If these three targets work, then the travis script should work. I hope that this helps.

**Comment by kohlhase** [comment]
thanks for the clarification. The main problem is that I can only partially build locally to test. 
But I found quite a few errors myself, and I will try to get further on my own.

**Comment by kohlhase** [comment]
I may have more questions over the weekend, until then, please just ignore the warnings.

**Comment by kohlhase** [comment]
> Travis seems to be getting a lot of errors now.

I seem to have fixed the errors, and seem to have the krc.bib-based architecture working. 
I still need to improve reference generation, but that should be possible now.

**Comment by kohlhase** [comment]
things have improved quite a lot, but there are still some fixes to do. 
- Steffen will work on the LaTeXML stuff
- I will improve the XSLT style sheets, so that the listings are more complete.

**Comment by tkw1536** [comment]
Can this be closed @kohlhase ?
